### ISSUE TITLE
Support URLs as call-to-action destination

### ISSUE THREAD

**Issue by kasparsd** [scottopolis/popup-zen#1]
I would love to use the plugin to promote content that doesn't require email signup. So instead of opening the email/name input fields, the "Learn More" button would actually take users to a different URL.

![link-instead](https://user-images.githubusercontent.com/169055/54999682-78852500-4fd9-11e9-8732-45c6786fc484.png)

This requires the following changes:

- Make "Fields" setting for each popup optional.
- Introduce a new URL destination field.

Would this be something valuable to the users? Happy to open a pull request with the suggested implementation.

**Comment by westaussie** [comment]
+1 for this idea :-)

An extension to this could be for the button to open the modal but don't show the signup form.

Use case:

Sale now on -> user clicks -> modal opens to show single image showing sale items or brochure first page ... no need to take the user anywhere if no URL. Also no need to show the sign up form.

**Comment by scottopolis** [comment]
Have you guys seen Holler Box? It does that: https://wordpress.org/plugins/holler-box

Popup Zen is focused on collecting emails, so I won't be making this change, sorry!
