### ISSUE TITLE
Hidden Popup Still Clickable

### ISSUE THREAD

**Issue by devinsays** [scottopolis/popup-zen#3]
When a visitor closes a popup, the `pzen-expanded` class is removed, and it defaults to these styles:

```
.popup-zen-box {
	opacity: 0;
	position: fixed;
	z-index: 99997;
	width: 100%;
	max-width: 325px;
	overflow: auto;
	...
}
```

Unfortunately, you can still interact with an element that has `opacity: 0`. I noticed it because our links are clickable even after the popup has been closed.

![Screen Shot 2019-05-28 at 4 11 57 PM](https://user-images.githubusercontent.com/431879/58512989-0c9f7400-8164-11e9-8b1a-9a61298947c5.png)

The box would need to have a `display: none` applied, moved offscreen, or removed from the DOM entirely.

Also, if someone closes the popup and then refreshes the screen, the popup is still hidden (opacity: 0), but it is present in the DOM. I think a better solution would be to check for the "hide" cookie before outputting the markup.

--

I'm happy to help with a fix for this if you're open to pull requests, but would need to know if there's any reason you're currently going with the current method. I.e., Would a popup that has been closed ever be activated at a later time in the same session (and therefore need the markup to be available)?

**Comment by scottopolis** [comment]
Confirmed, to replicate close the popup then refresh the page. pzen-hide class is removed, so the popup is still clickable.

**Comment by scottopolis** [comment]
@devinsays should be fixed with latest commit, can you test? eb43fcc29bfdabe514185b0eb217555734b7ab75

**Comment by devinsays** [comment]
Hey Scott. Yes, adding the `.pzen-hide` class fixed the issue.

Ideally none of the markup, css, or javascript would load if a popup is not going to be active (or potentially active on the page)- but this resolves the main bug.

Thanks for the plugin and quick turnaround!

**Comment by scottopolis** [comment]
Glad it worked. The markup will not show up on pages where the popup is not active, but in this case the popup is active but hidden.
